apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig
data:
  config.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://<your-kubernetes-api-server>
        certificate-authority-data: <your-certificate-authority-data>
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: <your-kubernetes-username>
      name: kubernetes
    current-context: kubernetes
    kind: Config
    preferences: {}
    users:
    - name: <your-kubernetes-username>
      user:
        token: <your-kubernetes-token>