apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-lambda-canary-controller
spec:
  selector:
    matchLabels:
      app: kubernetes-lambda-canary-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-lambda-canary-controller
    spec:
      serviceAccountName: kubernetes-lambda-canary-controller
      containers:
        - name: kubernetes-lambda-canary-controller
          image: <your-docker-registry>/kubernetes-lambda-canary-controller:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: kubeconfig
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig
